language: python
python:
  - "2.7"
install:  
  - pip install -r requirements.txt
  - pip install python-coveralls
# command to run tests
script:
  - python -m pycoincap.tests.test_core coveralls -v --cov coveralls
after_success:
  - coveralls
